[workspace]
members = ["crates/*", "generators/*"]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0.61"
tracing = "0.1.40"
windows = "0.56.0"
libc = "0.2.155"
vk-parse = "0.12.0"
ash = "0.38.0"
itertools = "0.13.0"

wie.path = "crates/wie"
wie-common.path = "crates/common"
wie-transport-vsock.path = "crates/transport-vsock"
wie-transport-guest.path = "crates/transport-guest"
wie-transport-host.path = "crates/transport-host"
