[package]
name = "wie-transport-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
simple_logger.workspace = true
wie-transport.workspace = true
wie-transport-vsock.workspace = true
