[package]
name = "wie-driver-listener-vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
ash.workspace = true
log.workspace = true
wie-transport.workspace = true
wie-transport-vsock.workspace = true
