[package]
name = "wie-driver-vulkan"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ash.workspace = true
wie-transport.workspace = true
wie-transport-guest.workspace = true
