[package]
name = "wie-driver-vulkan-generator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
vk-parse = { workspace = true, features = ["vkxml-convert"] }
vkxml.workspace = true
quote.workspace = true
proc-macro2.workspace = true
itertools.workspace = true
